# Generated by Django 3.1.7 on 2021-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad')], default='Cash On Delivery', max_length=20),
        ),
    ]
